# Generated by Django 3.0.5 on 2020-08-30 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200829_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Applicants'),
        ),
    ]
