# Generated by Django 3.0.5 on 2020-08-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200830_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='user',
            field=models.IntegerField(),
        ),
    ]
