# Generated by Django 3.0.5 on 2020-08-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200830_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registers',
            old_name='create_via',
            new_name='result',
        ),
    ]
